Item.create!(name: "Muladhara",		description: "Life")
Item.create!(name: "Svadishthana", 	description: "Order")
Item.create!(name: "Manipura", 		description: "Wisdom")
Item.create!(name: "Anahata", 		description: "Love")
Item.create!(name: "Visudda", 		description: "Power")
Item.create!(name: "Ajna", 		description: "Imagination")
Item.create!(name: "Sahasrara", 	description: "Understanding & Will")
